= Portrait

Cette appli permet de 
* Crawler des moteurs de recherche pour recupérér des images de et les stocker sur le disque.
* Reconnaître dans ces portraits une personne.
 
== Installation de opencv
 
 Il n'y a pas de lib ou de jar opencv accessible par maven.
Il faut donc:

* Recuperer opencv  sur son poste (https://opencv.org/releases/) ,
* Créer une lib; Window>preference>java>Build path>user lib avec les jar et dll de opencv precedemment importés.
* Importer la lib dans le projet eclipse: 
[Projet]>properties>java build pat>librairies>add Librairie>...
* Rajouter la lib precedemment créée

== Les points d'entrée

* bg.portrait.qwant.MainQWant :

Va recuperer des images sur le moteur de recheche qwant.

* bg.portrait.googleCSE.MainGoogleCSE :

Recherche d'images sur google CSE. Necessite d'avoir un compte sur CSE.

* bg.portrait.traitemment.MainParserImages :

Permet de parser l'ensemble des images récupérés (Pour les compter, les copier, faire des recherches etc...)

* bg.process.MainFaceRecognition

Applique un algo de reconnaissance à une image
